packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@trpc/client": 11.0.0-rc.502
  "@trpc/react-query": 11.0.0-rc.502
  "@trpc/server": 11.0.0-rc.502
  "dotenv-cli": 7.4.2
  prettier: 3.3.3
  typescript: 5.5.4
  zod: 3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.5
    "@types/react-dom": 18.3.0
